FROM node:20.11-alpine3.18 as build

RUN corepack enable

WORKDIR /app/submodules/atproto

COPY ./submodules/atproto/package.json ./
RUN corepack prepare --activate

COPY ./submodules/atproto/tsconfig ./tsconfig
# NOTE social-link's transitive dependencies go here: if that changes, this needs to be updated.
# pnpm ls --only-projects --parseable -F api... -F common... | sed 's#^.*atproto/##'
COPY ./submodules/atproto/packages/api/package.json ./packages/api/package.json
COPY ./submodules/atproto/packages/common/package.json ./packages/common/package.json
COPY ./submodules/atproto/packages/common-web/package.json ./packages/common-web/package.json
COPY ./submodules/atproto/packages/lex-cli/package.json ./packages/lex-cli/package.json
COPY ./submodules/atproto/packages/lex/lex-cbor/package.json ./packages/lex/lex-cbor/package.json
COPY ./submodules/atproto/packages/lex/lex-data/package.json ./packages/lex/lex-data/package.json
COPY ./submodules/atproto/packages/lex/lex-json/package.json ./packages/lex/lex-json/package.json
COPY ./submodules/atproto/packages/lexicon/package.json ./packages/lexicon/package.json
COPY ./submodules/atproto/packages/syntax/package.json ./packages/syntax/package.json
COPY ./submodules/atproto/packages/xrpc/package.json ./packages/xrpc/package.json
COPY ./submodules/atproto/package.json ./package.json
COPY ./submodules/atproto/pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./submodules/atproto/pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN pnpm install --frozen-lockfile

COPY ./submodules/atproto/*.js* ./
# NOTE matching transitive dependencies from above
COPY ./submodules/atproto/packages/api ./packages/api
COPY ./submodules/atproto/packages/common ./packages/common
COPY ./submodules/atproto/packages/common-web ./packages/common-web
COPY ./submodules/atproto/packages/lex-cli ./packages/lex-cli
COPY ./submodules/atproto/packages/lex/lex-cbor ./packages/lex/lex-cbor
COPY ./submodules/atproto/packages/lex/lex-data ./packages/lex/lex-data
COPY ./submodules/atproto/packages/lex/lex-json ./packages/lex/lex-json
COPY ./submodules/atproto/packages/lexicon ./packages/lexicon
COPY ./submodules/atproto/packages/syntax ./packages/syntax
COPY ./submodules/atproto/packages/xrpc ./packages/xrpc

# build all packages with external node_modules
RUN pnpm build
# clean up
# RUN rm -rf node_modules
# install only prod deps, hoisted to root node_modules dir
# RUN pnpm install --prod --shamefully-hoist --frozen-lockfile --prefer-offline > /dev/null

# Copy conf files
WORKDIR /app/conf

COPY ./conf ./

# Move files into the image and install
WORKDIR /app/bskylink

COPY ./bskylink/package.json ./
COPY ./bskylink/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./bskylink/*.json ./
COPY ./bskylink/src ./src
COPY ./bskylink/locales ./locales

# build then prune dev deps
RUN yarn build
RUN yarn install --production --ignore-scripts --prefer-offline

# Uses assets from build stage to reduce build size
FROM node:20.11-alpine3.18

RUN apk add --update dumb-init

# Avoid zombie processes, handle signal forwarding
ENTRYPOINT ["dumb-init", "--"]

WORKDIR /app/bskylink
COPY --from=build /app/submodules/atproto/ /app/submodules/atproto/
COPY --from=build /app/bskylink /app/bskylink
RUN mkdir /app/data && chown node /app/data

VOLUME /app/data
EXPOSE 3000
ARG LINK_VERSION
ENV LINK_VERSION=${LINK_VERSION}
ENV LINK_PORT=3000
ENV NODE_ENV=production
# potential perf issues w/ io_uring on this version of node
ENV UV_USE_IO_URING=0

# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
USER node
CMD ["node", "--heapsnapshot-signal=SIGUSR2", "--enable-source-maps", "dist/bin.js"]

LABEL org.opencontainers.image.source=https://github.com/bluesky-social/social-app
LABEL org.opencontainers.image.description="Bsky Link Service"
LABEL org.opencontainers.image.licenses=UNLICENSED
