FROM node:20.11-alpine3.18 as build

ARG SOCIAL_APP_NAME
ENV SOCIAL_APP_NAME=${SOCIAL_APP_NAME}

RUN corepack enable

WORKDIR /atproto

COPY --from=atproto /package.json ./
RUN corepack prepare --activate

COPY --from=atproto ./tsconfig ./tsconfig
COPY --from=atproto ./packages/api/package.json ./packages/api/package.json
COPY --from=atproto ./packages/common-web/package.json ./packages/common-web/package.json
COPY --from=atproto ./packages/syntax/package.json ./packages/syntax/package.json
COPY --from=atproto ./packages/lexicon/package.json ./packages/lexicon/package.json
COPY --from=atproto ./packages/xrpc/package.json ./packages/xrpc/package.json
COPY --from=atproto ./package.json ./package.json
COPY --from=atproto ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=atproto ./pnpm-workspace.yaml ./pnpm-workspace.yaml 

RUN pnpm install --frozen-lockfile

# COPY --from=atproto / .

COPY --from=atproto ./*.js* ./
# NOTE api's transitive dependencies go here: if that changes, this needs to be updated.
COPY --from=atproto ./tsconfig ./tsconfig
COPY --from=atproto ./packages/api ./packages/api
COPY --from=atproto ./packages/common-web ./packages/common-web
COPY --from=atproto ./packages/syntax ./packages/syntax
COPY --from=atproto ./packages/lexicon ./packages/lexicon
COPY --from=atproto ./packages/xrpc ./packages/xrpc
# build all packages with external node_modules
RUN pnpm build
# clean up
# RUN rm -rf node_modules
# install only prod deps, hoisted to root node_modules dir
# RUN pnpm install --prod --shamefully-hoist --frozen-lockfile --prefer-offline > /dev/null

# Move files into the image and install
WORKDIR /app/bskyogcard

COPY ./bskyogcard/package.json ./
COPY ./bskyogcard/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./bskyogcard/*.json ./
COPY ./bskyogcard/src ./src
COPY ./bskyogcard/scripts ./scripts

# build then prune dev deps
RUN yarn install-fonts && yarn build
RUN yarn install --production --ignore-scripts --prefer-offline

# Uses assets from build stage to reduce build size
FROM node:20.11-alpine3.18

RUN apk add --update dumb-init

# Avoid zombie processes, handle signal forwarding
ENTRYPOINT ["dumb-init", "--"]

WORKDIR /app/bskyogcard
COPY --from=build /atproto/ /atproto/
COPY --from=build /app/bskyogcard /app/bskyogcard
RUN mkdir /app/data && chown node /app/data

VOLUME /app/data
EXPOSE 3000
ARG CARD_VERSION
ENV CARD_VERSION=${CARD_VERSION}
ENV CARD_PORT=3000
ENV NODE_ENV=production
# potential perf issues w/ io_uring on this version of node
ENV UV_USE_IO_URING=0

# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
USER node
CMD ["node", "--heapsnapshot-signal=SIGUSR2", "--enable-source-maps", "dist/bin.js"]

LABEL org.opencontainers.image.source=https://github.com/bluesky-social/social-app
LABEL org.opencontainers.image.description="Bsky Card Service"
LABEL org.opencontainers.image.licenses=UNLICENSED
