FROM node:20-alpine3.22 as build-node

RUN corepack enable

WORKDIR /usr/src/social-app/submodules/atproto

COPY ./submodules/atproto/package.json ./
RUN corepack prepare --activate

COPY ./submodules/atproto/tsconfig ./tsconfig
COPY ./submodules/atproto/packages/api/package.json ./packages/api/package.json
COPY ./submodules/atproto/packages/common-web/package.json ./packages/common-web/package.json
COPY ./submodules/atproto/packages/syntax/package.json ./packages/syntax/package.json
COPY ./submodules/atproto/packages/lexicon/package.json ./packages/lexicon/package.json
COPY ./submodules/atproto/packages/xrpc/package.json ./packages/xrpc/package.json
COPY ./submodules/atproto/package.json ./package.json
COPY ./submodules/atproto/pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./submodules/atproto/pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN pnpm install --frozen-lockfile

# COPY ./submodules/atproto/ .

COPY ./submodules/atproto/*.js* ./
# NOTE api's transitive dependencies go here: if that changes, this needs to be updated.
COPY ./submodules/atproto/tsconfig ./tsconfig
COPY ./submodules/atproto/packages/api ./packages/api
COPY ./submodules/atproto/packages/common-web ./packages/common-web
COPY ./submodules/atproto/packages/syntax ./packages/syntax
COPY ./submodules/atproto/packages/lexicon ./packages/lexicon
COPY ./submodules/atproto/packages/xrpc ./packages/xrpc
# build all packages with external node_modules
RUN pnpm build
# clean up
# RUN rm -rf node_modules
# install only prod deps, hoisted to root node_modules dir
# RUN pnpm install --prod --shamefully-hoist --frozen-lockfile --prefer-offline > /dev/null

WORKDIR /usr/src/social-app/

# Node
ENV NODE_VERSION=20
ENV NVM_DIR=/usr/share/nvm

COPY ./package.json .
COPY ./scripts ./scripts

RUN corepack prepare --activate

COPY ./bskyembed ./bskyembed
COPY ./bskyweb ./bskyweb
COPY ./conf/branding.json ./bskyweb/branding.json
#
# Generate the JavaScript webpack. NOTE: this will change
#
RUN cd bskyembed && yarn install --frozen-lockfile && cd .. && \
  yarn build-embed

# hack around issue with empty directory and go:embed
RUN touch bskyweb/static/js/empty.txt
RUN touch bskyweb/static/css/empty.txt
RUN touch bskyweb/static/media/empty.txt

FROM golang:1.24.5-bullseye AS build-env

WORKDIR /usr/src/social-app

COPY --from=build-node /usr/src/social-app/bskyembed /usr/src/social-app/bskyembed
COPY --from=build-node /usr/src/social-app/bskyweb /usr/src/social-app/bskyweb

ENV DEBIAN_FRONTEND=noninteractive

# Go
ENV GODEBUG="netdns=go"
ENV GOOS="linux"
ENV CGO_ENABLED=1
ENV GOEXPERIMENT="loopvar"


#
# Generate the embedr Go binary.
#

RUN cd bskyweb/ && \
  go mod download && \
  go mod verify

RUN cd bskyweb/ && \
  go build \
    -v  \
    -trimpath \
    -tags timetzdata \
    -o /embedr \
    ./cmd/embedr

FROM debian:bullseye-slim

ENV GODEBUG=netdns=go
ENV TZ=Etc/UTC
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --yes \
  dumb-init \
  ca-certificates

ENTRYPOINT ["dumb-init", "--"]

WORKDIR /embedr
COPY --from=build-env /embedr /usr/bin/embedr

CMD ["/usr/bin/embedr"]

LABEL org.opencontainers.image.source=https://github.com/bluesky-social/social-app
LABEL org.opencontainers.image.description="embed.bsky.app Web App"
LABEL org.opencontainers.image.licenses=MIT
